AWSTemplateFormatVersion: "2010-09-09"
Description: Gateway VPC Endpoint Template

# -----------------------------------------------------------------
# 入力パラメータ
# -----------------------------------------------------------------
Parameters:
  # VPC ID
  VpcId:
    Description : "VPC ID"
    Type: AWS::EC2::VPC::Id
  # ルートテーブルID 1つ目
  RouteTableId1:
    Description : "Gateway 1st Route Table ID"
    Type : String
  # ルートテーブルID 2つ目
  RouteTableId2:
    Description : "Gateway 2nd Route Table ID"
    Type : String

Resources:
  # -----------------------------------------------------------------
  # S3アクセス用のエンドポイントを作成
  # -----------------------------------------------------------------
  tempalteS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .s3
      VpcId: !Ref 'VpcId'
      RouteTableIds:
        - !Ref RouteTableId1
        - !Ref RouteTableId2
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource:
              - 'arn:aws:s3:::examplebucket/*'
