# ---------------------------------------------------------
# ネットワーク編 セキュリティグループ（踏み台用）
# ---------------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"
Description: Network Security Group Template

# ---------------------------------------------------------
# パラメータ
# ---------------------------------------------------------
Parameters:
  System:
    Description: System Name
    Type: String
    Default: template
  Function:
    Description: Function Name
    Type: String
    Default: ""
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

# ---------------------------------------------------------
# リソース
# ---------------------------------------------------------
Resources:
  # -------------------------------------------------------
  # セキュリティグループを作成
  # -------------------------------------------------------
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref VpcId
      GroupDescription: !Sub Security Group attached to ${Function}
      GroupName: !Sub ${System}-sg-${Function}

  # -------------------------------------------------------
  # Ingress セキュリティルールを作成 ※カスタマイズ
  # -------------------------------------------------------
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: SSH Port
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      FromPort: 22
      ToPort: 22
      GroupId: !GetAtt SecurityGroup.GroupId

# ---------------------------------------------------------
# アウトプット
# ---------------------------------------------------------
Outputs:
  SecurityGroupId:
    Value: !Ref SecurityGroup
    Description: Security Group ID
