# ---------------------------------------------------------
# ネットワーク編 NATゲートウェイ
# ---------------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"
Description: Network NAT Gateway Template

# ---------------------------------------------------------
# パラメータ
# ---------------------------------------------------------
Parameters:
  System:
    Description: System Name
    Type: String
    Default: template
  AvailabilityZoneNo:
    Description: Aveilability Zone Number
    Type: Number
    Default: 0
  SubnetId:
    Description: Subnet ID
    Type: AWS::EC2::Subnet::Id

# ---------------------------------------------------------
# リソース
# ---------------------------------------------------------
Resources:
  # -------------------------------------------------------
  # Elastic IPを作成
  # -------------------------------------------------------
  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub ${System}-eip-${AvailabilityZoneNo}

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIp.AllocationId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub ${System}-ngw-${AvailabilityZoneNo}
  

# ---------------------------------------------------------
# アウトプット
# ---------------------------------------------------------
Outputs:
  NatGatewayId:
    Value: !Ref NatGateway
    Description: NAT Gateway ID
