# ---------------------------------------------------------
# パブリック x2 ネットワーク構成
# ---------------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"
Description: Public x2 Network

# ---------------------------------------------------------
# パラメータ
# ---------------------------------------------------------
Parameters:
  System:
    Description: System Name
    Type: String
    Default: template

  VpcTemplateUrl:
    Description: VPC template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-vpc.yml

  InternetGatewayTemplateUrl:
    Description: Internet Gateway template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-internet-gateway.yml

  PublicSubnetTemplateUrl:
    Description: Public Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-public-subnet.yml

  NatGatewayTemplateUrl:
    Description: Public Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-nat-gateway.yml

  PrivateSubnetTemplateUrl:
    Description: Private Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-private-subnet.yml

  SecurityGroupTemplateUrl:
    Description: Security Group template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-security-group.yml


# ---------------------------------------------------------
# リソース
# ---------------------------------------------------------
Resources:
  # ----------------------------------
  # VPC 作成
  # ----------------------------------
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateUrl
      Parameters:
        System: template

  # ----------------------------------
  # インターネットゲートウェイ 作成
  # ----------------------------------
  InternetGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref InternetGatewayTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: VPC

  # ----------------------------------
  # パブリックサブネット1 作成
  # ----------------------------------
  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PublicSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt InternetGateway.Outputs.InternetGatewayId
        AvailabilityZoneNo: 0
        CidrBlock: 10.0.0.0/20
    DependsOn: InternetGateway

  # ----------------------------------
  # パブリックサブネット2 作成
  # ----------------------------------
  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PublicSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt InternetGateway.Outputs.InternetGatewayId
        AvailabilityZoneNo: 1
        CidrBlock: 10.0.16.0/20
    DependsOn: InternetGateway

  # ----------------------------------
  # NATゲートウェイ1 作成
  # ----------------------------------
  NatGateway1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NatGatewayTemplateUrl
      Parameters: 
        System: template
        AvailabilityZoneNo: 0
        SubnetId: !GetAtt PublicSubnet1.Outputs.PublicSubnetId
    DependsOn: PublicSubnet1

  # ----------------------------------
  # NATゲートウェイ2 作成
  # ----------------------------------
  NatGateway2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NatGatewayTemplateUrl
      Parameters: 
        System: template
        AvailabilityZoneNo: 1
        SubnetId: !GetAtt PublicSubnet2.Outputs.PublicSubnetId
    DependsOn: PublicSubnet2

  # ----------------------------------
  # プライベートサブネット1 作成
  # ----------------------------------
  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PrivateSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        AvailabilityZoneNo: 0
        CidrBlock: 10.0.64.0/20
        NatGatewayId: !GetAtt NatGateway1.Outputs.NatGatewayId
    DependsOn: NatGateway1

  # ----------------------------------
  # プライベートサブネット2 作成
  # ----------------------------------
  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PrivateSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        AvailabilityZoneNo: 1
        CidrBlock: 10.0.80.0/20
        NatGatewayId: !GetAtt NatGateway2.Outputs.NatGatewayId
    DependsOn: NatGateway2

  # ----------------------------------
  # 踏み台用セキュリティグループ 作成
  # ----------------------------------
  BastionSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupTemplateUrl
      Parameters: 
        System: template
        Function: bastion
        VpcId: !GetAtt VPC.Outputs.VpcId
        AllowedIp: 0.0.0.0/0
    DependsOn: PrivateSubnet1