# ---------------------------------------------------------
# パブリック x2 ネットワーク構成
# ---------------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"
Description: Public x2 Network

# ---------------------------------------------------------
# パラメータ
# ---------------------------------------------------------
Parameters:
  System:
    Description: System Name
    Type: String
    Default: template
  
  VpcTemplateUrl:
    Description: VPC template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-vpc.yml

  InternetGatewayTemplateUrl:
    Description: Internet Gateway template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-internet-gateway.yml

  PublicSubnetTemplateUrl:
    Description: Public Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-public-subnet.yml

  NatGatewayTemplateUrl:
    Description: Public Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-nat-gateway.yml

  PrivateSubnetTemplateUrl:
    Description: Private Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-private-subnet.yml

  SecurityGroupTemplateUrl:
    Description: Security Group template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-security-group.yml

  SecurityGroupRuleBastionTemplateUrl:
    Description: Security Group Rule Bastion template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-sg-rule-bastion.yml

  SecurityGroupRuleAppTemplateUrl:
    Description: Security Group Rule App template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-sg-rule-app.yml

  SecurityGroupRuleLoadBalancerTemplateUrl:
    Description: Security Group Rule Load Balancer template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network/network-sg-rule-elb.yml

  # -------------------------------------------------------
  # ここからアプリケーション
  # -------------------------------------------------------
  BastionEc2TemplateUrl:
    Description: Bastion EC2 template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/ec2/ec2-bastion.yml

  BaseEc2TemplateUrl:
    Description: Base EC2 template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/ec2/ec2-base.yml

  LoadBalancerTemplateUrl:
    Description: Load Balancer EC2 template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/ec2/ec2-elb.yml

# ---------------------------------------------------------
# リソース
# ---------------------------------------------------------
Resources:
  # ----------------------------------
  # VPC 作成
  # ----------------------------------
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateUrl
      Parameters:
        System: template

  # ----------------------------------
  # インターネットゲートウェイ 作成
  # ----------------------------------
  InternetGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref InternetGatewayTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: VPC

  # ----------------------------------
  # パブリックサブネット1 作成
  # ----------------------------------
  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PublicSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt InternetGateway.Outputs.InternetGatewayId
        AvailabilityZoneNo: 0
        CidrBlock: 10.0.0.0/20
    DependsOn: InternetGateway

  # ----------------------------------
  # パブリックサブネット2 作成
  # ----------------------------------
  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PublicSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt InternetGateway.Outputs.InternetGatewayId
        AvailabilityZoneNo: 1
        CidrBlock: 10.0.16.0/20
    DependsOn: InternetGateway

  # ----------------------------------
  # NATゲートウェイ1 作成
  # ----------------------------------
  NatGateway1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NatGatewayTemplateUrl
      Parameters: 
        System: template
        AvailabilityZoneNo: 0
        SubnetId: !GetAtt PublicSubnet1.Outputs.PublicSubnetId
    DependsOn: PublicSubnet1

  # ----------------------------------
  # NATゲートウェイ2 作成
  # ----------------------------------
  NatGateway2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NatGatewayTemplateUrl
      Parameters: 
        System: template
        AvailabilityZoneNo: 1
        SubnetId: !GetAtt PublicSubnet2.Outputs.PublicSubnetId
    DependsOn: PublicSubnet2

  # ----------------------------------
  # プライベートサブネット1 作成
  # ----------------------------------
  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PrivateSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        AvailabilityZoneNo: 0
        CidrBlock: 10.0.64.0/20
        NatGatewayId: !GetAtt NatGateway1.Outputs.NatGatewayId
    DependsOn: NatGateway1

  # ----------------------------------
  # プライベートサブネット2 作成
  # ----------------------------------
  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PrivateSubnetTemplateUrl
      Parameters: 
        System: template
        VpcId: !GetAtt VPC.Outputs.VpcId
        AvailabilityZoneNo: 1
        CidrBlock: 10.0.80.0/20
        NatGatewayId: !GetAtt NatGateway2.Outputs.NatGatewayId
    DependsOn: NatGateway2

  # ----------------------------------
  # 踏み台用セキュリティグループ 作成
  # ----------------------------------
  BastionSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupTemplateUrl
      Parameters: 
        System: template
        Function: bastion
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: PublicSubnet1

  # ----------------------------------
  # ロードバランサー用セキュリティグループ 作成
  # ----------------------------------
  LoadBalancerSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupTemplateUrl
      Parameters: 
        System: template
        Function: elb
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: PrivateSubnet1

  # ----------------------------------
  # アプリケーション用セキュリティグループ 作成
  # ----------------------------------
  AppSecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupTemplateUrl
      Parameters: 
        System: template
        Function: app
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: PrivateSubnet1

  # ----------------------------------
  # 踏み台用セキュリティグループルール作成
  # ----------------------------------
  BastionSecurityGroupRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupRuleBastionTemplateUrl
      Parameters: 
        System: template
        Function: bastion
        AssociateSecurityGroupId: !GetAtt BastionSecurityGroup.Outputs.SecurityGroupId
    DependsOn: BastionSecurityGroup

  # ----------------------------------
  # ロードバランサー用セキュリティグループルール作成
  # ----------------------------------
  LoadBalancerSecurityGroupRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupRuleLoadBalancerTemplateUrl
      Parameters: 
        System: template
        Function: elb
        AssociateSecurityGroupId: !GetAtt LoadBalancerSecurityGroup.Outputs.SecurityGroupId
    DependsOn: LoadBalancerSecurityGroup

  # ----------------------------------
  # アプリケーション用セキュリティグループルール作成
  # ----------------------------------
  AppSecurityGroupRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityGroupRuleAppTemplateUrl
      Parameters: 
        System: template
        Function: app
        AssociateSecurityGroupId: !GetAtt AppSecurityGroup.Outputs.SecurityGroupId
        SshSecurityGroupId: !GetAtt BastionSecurityGroup.Outputs.SecurityGroupId
        HttpSecurityGroupId: !GetAtt LoadBalancerSecurityGroup.Outputs.SecurityGroupId
    DependsOn: AppSecurityGroup


  # -------------------------------------------------------
  # ここからアプリケーション
  # -------------------------------------------------------
  BastionEc2Instanace:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BastionEc2TemplateUrl
      Parameters: 
        System: template
        KeyPair: template-keypair
        SubnetId: !GetAtt PublicSubnet1.Outputs.PublicSubnetId
        SecurityGroupId: !GetAtt BastionSecurityGroup.Outputs.SecurityGroupId
    DependsOn: [BastionSecurityGroup, PublicSubnet1]

  WebEc2Instanace1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BaseEc2TemplateUrl
      Parameters:
        System: template
        InstanceName: web-0
        KeyPair: template-keypair
        SubnetId: !GetAtt PrivateSubnet1.Outputs.PrivateSubnetId
        SecurityGroupId: !GetAtt AppSecurityGroup.Outputs.SecurityGroupId
    DependsOn: [AppSecurityGroup, PrivateSubnet1]

  WebEc2Instanace2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BaseEc2TemplateUrl
      Parameters:
        System: template
        InstanceName: web-1
        KeyPair: template-keypair
        SubnetId: !GetAtt PrivateSubnet2.Outputs.PrivateSubnetId
        SecurityGroupId: !GetAtt AppSecurityGroup.Outputs.SecurityGroupId
    DependsOn: [AppSecurityGroup, PrivateSubnet2]

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref LoadBalancerTemplateUrl
      Parameters:
        System: template
        Function: web
        VpcId: !GetAtt VPC.Outputs.VpcId
        SubnetIds: !Join [",", [!GetAtt PublicSubnet1.Outputs.PublicSubnetId, !GetAtt PublicSubnet2.Outputs.PublicSubnetId]]
        TargetInstances: !Join [",", [!GetAtt WebEc2Instanace1.Outputs.Ec2InstanceId, !GetAtt WebEc2Instanace2.Outputs.Ec2InstanceId]]
        SecurityGoupIds: !Join [",", [!GetAtt LoadBalancerSecurityGroup.Outputs.SecurityGroupId]]
    DependsOn: [LoadBalancerSecurityGroup, WebEc2Instanace1, WebEc2Instanace2]

Outputs: 
  BastionEc2InstanacePublicIpAddress:
    Description: Bastion Instanace Public IP Addresss
    Value: !GetAtt BastionEc2Instanace.Outputs.Ec2InstanceLPublicIp
  BastionEc2InstanacePrivateIpAddress:
    Description: Bastion Instanace Private IP Addresss
    Value: !GetAtt BastionEc2Instanace.Outputs.Ec2InstanceLPrivateIp
  WebEc2Instanace1IpAddress:
    Description: Web Instanace 1 Private IP Addresss
    Value: !GetAtt WebEc2Instanace1.Outputs.Ec2InstanceLPrivateIp
  WebEc2Instanace2IpAddress:
    Description: Web Instanace 2 Private IP Addresss
    Value: !GetAtt WebEc2Instanace2.Outputs.Ec2InstanceLPrivateIp
  LoadBalancerDnsName:
    Description: Load Blancer DNS Name
    Value: !GetAtt LoadBalancer.Outputs.LoadBalancerDnsName
  