AWSTemplateFormatVersion: "2010-09-09"
Description: Network Security Group Template

Parameters:
  # -----------------------------------------------------------------
  # for Security Group
  # -----------------------------------------------------------------
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  SshAllowedIp:
    Description: IP address you want to access with SSH
    Type: String
    Default: "0.0.0.0/0"
  
Resources:
  # -----------------------------------------------------------------
  # セキュリティグループ (SSH アクセス許可)
  # -----------------------------------------------------------------  
  templateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId: !Ref VpcId
      GroupDescription: "Scurity Group for template EC2"
      GroupName: "template-ec2-sg"
      SecurityGroupIngress:
        -   CidrIp: !Ref SshAllowedIp
            Description: SSH Port
            FromPort: 22
            IpProtocol: tcp
            ToPort: 22

Outputs:
  SecurityGroupId:
    Value: !Ref templateSecurityGroup
    Description: Security Group ID

