AWSTemplateFormatVersion: "2010-09-09"
Description: Network Root Template

Parameters:
  TemplateVpc:
    Description: VPC template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network-vpc.yml

  TemplateInternetGateway:
    Description: Internet Gateway template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network-internet-gateway.yml

  TemplatePublicSubnet:
    Description: Public Subnet template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network-public-subnet.yml

  TemplateSecurityGroup:
    Description: Securiy Group template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/network-security-group.yml

  TemplateEC2:
    Description: EC2 template URL
    Type: String
    Default: https://template-bucket-template.s3.ap-northeast-3.amazonaws.com/template/ec2.yml

Resources:
  # ----------------------------------------------------------
  # VPCの作成
  # ----------------------------------------------------------
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateVpc
      Parameters:
        VpcName: template-vpc

  # ----------------------------------------------------------
  # Internet Gatewayの作成
  # ----------------------------------------------------------
  InternetGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateInternetGateway
      Parameters: 
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: VPC

  # ----------------------------------------------------------
  # Subnetの作成
  # ----------------------------------------------------------
  PublicSubnet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplatePublicSubnet
      Parameters: 
        VpcId: !GetAtt VPC.Outputs.VpcId
        InternetGatewayId: !GetAtt InternetGateway.Outputs.InternetGatewayId
    DependsOn: InternetGateway

  # ----------------------------------------------------------
  # Security Groupの作成
  # ----------------------------------------------------------
  SecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateSecurityGroup
      Parameters:
        VpcId: !GetAtt VPC.Outputs.VpcId
    DependsOn: VPC

  # ----------------------------------------------------------
  # EC2の作成
  # ----------------------------------------------------------
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateEC2
      Parameters: 
        SubnetId: !GetAtt PublicSubnet.Outputs.PublicSubnetId
        SecurityGroupId: !GetAtt SecurityGroup.Outputs.SecurityGroupId
    DependsOn: 
      - SecurityGroup
      - PublicSubnet